name: device_tracking
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  cloud_firestore: ^3.5.1
  google_maps_flutter: 2.2.1
  get: 4.6.5
  get_storage: 2.0.3
  uuid: 3.0.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/device.png
    - assets/images/maps.png
    - assets/images/history.png
    - assets/images/account.png
    - assets/images/sos.png
  uses-material-design: true

